### PR TITLE
Upgrade to 1.19

### PR DESCRIPTION
**Pull request by mrmelon54**

### CODE REVIEW

**Comment by jtenner** [comment]
Hey I've been waiting for this! any ETA on this?

**Comment by mrmelon54** [comment]
this is a PR from my fork.. I can upload a prebuilt copy if you want

**Comment by jtenner** [comment]
Yeah that would be awesome. Has work been done on all the other "extended enchantments" mods too? I'd love to help if I can.

**Comment by mrmelon54** [comment]
I make a PR updating all 4 expanded enchantment mods to 1.19...

I can upload a prebuilt jar of all of them if you want

**Comment by SmushyTaco** [comment]
I'm planning on updating all my mods a week after 1.19.1 is released.

**Comment by mrmelon54** [comment]
> I'm planning on updating all my mods a week after 1.19.1 is released.

Well I've already provided you with 1.19 PRs so that would get you started

**Comment by mrmelon54** [comment]
> Yeah that would be awesome. Has work been done on all the other "extended enchantments" mods too? I'd love to help if I can.

[expanded-enchanting-mods.zip](https://github.com/SmushyTaco/Expanded-Armor-Enchanting/files/9031422/expanded-enchanting-mods.zip)

**Comment by jtenner** [comment]
> > Yeah that would be awesome. Has work been done on all the other "extended enchantments" mods too? I'd love to help if I can.
> 
> [expanded-enchanting-mods.zip](https://github.com/SmushyTaco/Expanded-Armor-Enchanting/files/9031422/expanded-enchanting-mods.zip)

Thank you very very much!

**Pull request closed without merging**
